sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  code_climate:
    repo_token: 'a859074f235c0f058415d9e0a6b8595523b5eebbd211e5a8866620007b9cef0b'
language: node_js
node_js:
  - stable
before_script:
  - npm install -g @angular/cli
# install:
#   - npm install
script:
  - npm run test-headless
# before_script:
#   - export DISPLAY=:99.0
#   - sh -e /etc/init.d/xvfb start
#   - sleep 3
notifications:
  email: false
# after_success:
#   - npm install -g codeclimate-test-reporter
#   - codeclimate-test-reporter < lcov.info